name: run_tests
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
